Add project task-list-app-maui in MauiSamples
VladislavAntonyuk/MauiSamples pull request #375
Opened 2023-10-04 17:18 UTC by jfs-dev

Hello! @VladislavAntonyuk 

1. Add folder task-list-app-maui;
2. Edit MauiSamples.sln for add project task-list-app-maui;
3. Edit README.md for add link and description the project task-list-app-maui.

Best Regards.

2023-10-04 20:18 UTC, VladislavAntonyuk requested changes

2023-10-04 20:18 UTC, VladislavAntonyuk commented on README.md
> +1. [task-list-app-maui](task-list-app-maui) - Cross-platform .NET MAUI app using MVVM development architecture performing CRUD operations with EF Core InMemory.
Update readme.mdpp file instead. This file is auto generated

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/AppShell.xaml
> +    <!-- <ShellContent
Please remove comments

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/AppShell.xaml
> +        <ToolbarItem Text="Pesquisar"
If possible could you please translate to English?

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Data/AppDbContext.cs
> +    public DbSet<Tarefa> Tarefas { get; set; }
```suggestion
    public DbSet<Tarefa> Tarefas => Set<Tarefa>;
```

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/MainPage.xaml
> +<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
Seems like this page is not used. Please remove it

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Resources/Splash/_splash.svg
> +<svg width="456" height="456" viewBox="0 0 456 456" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/
Probably can be removed

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            _context.Entry(Tarefa).State = EntityState.Added;
Use context.Tarefas.Add(tarefa)

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            _context.Entry(Tarefa).State = EntityState.Modified;
This is automatically handled by efcore and can be removed

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            _context.Entry(Tarefa).State = EntityState.Deleted;
Use remove instead

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +        foreach (var tarefa in _context.Tarefas.Where(x => x.Concluida == false).OrderBy(x => x.Data + x.Hora).ToList())
You can instead make only one request to db and filter in memory

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/AdicionarTarefaView.xaml
> +            <Grid.RowDefinitions>
Use simpler syntax Height="Auto,Auto..."

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/AdicionarTarefaView.xaml
> +        <StackLayout VerticalOptions="EndAndExpand"
Use HorizontalStackLayout and remove all AndExpand

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/EditarTarefaView.xaml
> +    <StackLayout Padding="20">
Don't use StackLayout. This page can be rewritten using single Grid

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/TarefasConcluidasView.xaml
> +        <ListView x:Name="ListViewTarefasConcluidas"
Use CollectionView and don't use StackLayout

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/TarefasPendentesView.xaml
> +        <ListView x:Name="ListViewTarefasPendentes"
This page looks similar to the previous. Can we reuse it?

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/TarefasPendentesView.xaml.cs
> +public partial class TarefasPendentesView : ContentPage
This seems to be the same as previous page.

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/task-list-app-maui.csproj
> +		<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
Use NetVersion instead

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/task-list-app-maui.csproj
> +		<ImplicitUsings>enable</ImplicitUsings>
Please remove duplicates (see other projects)

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/task-list-app-maui.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.11" />
Why not to use efcore 8?

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/task-list-app-maui.csproj.user
> +<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Please remove

2023-10-04 20:18 UTC, VladislavAntonyuk commented on task-list-app-maui/task-list-app-maui.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Please remove

2023-10-05 17:05 UTC, jfs-dev commented on task-list-app-maui/MainPage.xaml
> +            <Image
Interface removed, not used

2023-10-05 17:05 UTC, jfs-dev commented on task-list-app-maui/MainPage.xaml
> +            <Button
Interface removed, not used

2023-10-05 17:34 UTC, jfs-dev commented on README.md
> +1. [task-list-app-maui](task-list-app-maui) - Cross-platform .NET MAUI app using MVVM development architecture performing CRUD operations with EF Core InMemory.
Update readme.mdpp OK

2023-10-05 18:08 UTC, jfs-dev commented on task-list-app-maui/AppShell.xaml
> +    <!-- <ShellContent
Comments removed

2023-10-05 18:09 UTC, jfs-dev commented on task-list-app-maui/AppShell.xaml
> +        <ToolbarItem Text="Pesquisar"
Translate to English Ok

2023-10-05 18:14 UTC, jfs-dev commented on task-list-app-maui/MainPage.xaml
> +<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
Interface removed

2023-10-05 18:22 UTC, jfs-dev commented on task-list-app-maui/Data/AppDbContext.cs
> +    public DbSet<Tarefa> Tarefas { get; set; }
Suggestion accepted

2023-10-05 18:25 UTC, jfs-dev commented on task-list-app-maui/task-list-app-maui.csproj.user
> +<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
File removed

2023-10-05 18:26 UTC, jfs-dev commented on task-list-app-maui/task-list-app-maui.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
File removed

2023-10-05 18:58 UTC, jfs-dev commented on task-list-app-maui/task-list-app-maui.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.11" />
Update Successfully

2023-10-05 20:27 UTC, jfs-dev commented on task-list-app-maui/task-list-app-maui.csproj
> +		<ImplicitUsings>enable</ImplicitUsings>
Duplicates removed

2023-10-05 20:32 UTC, jfs-dev commented on task-list-app-maui/task-list-app-maui.csproj
> +		<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
Removed TargetFrameworks

2023-10-05 20:47 UTC, VladislavAntonyuk commented on task-list-app-maui/task-list-app-maui.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.11" />
I plan to update to .NET 8 with rc2.after that it will work

2023-10-10 16:44 UTC, jfs-dev commented on task-list-app-maui/Resources/Splash/_splash.svg
> +<svg width="456" height="456" viewBox="0 0 456 456" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/
Yes! File removed

2023-10-10 17:02 UTC, jfs-dev commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            _context.Entry(Tarefa).State = EntityState.Added;
OK

2023-10-10 17:02 UTC, jfs-dev commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            _context.Entry(Tarefa).State = EntityState.Modified;
Removed

2023-10-10 17:02 UTC, jfs-dev commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            _context.Entry(Tarefa).State = EntityState.Deleted;
OK

2023-10-10 17:02 UTC, jfs-dev commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +        foreach (var tarefa in _context.Tarefas.Where(x => x.Concluida == false).OrderBy(x => x.Data + x.Hora).ToList())
OK

2023-10-11 17:43 UTC, jfs-dev commented on task-list-app-maui/Views/AdicionarTarefaView.xaml
> +            <Grid.RowDefinitions>
Using the grid, it was necessary to adjust the size of the lines

2023-10-11 17:44 UTC, jfs-dev commented on task-list-app-maui/Views/AdicionarTarefaView.xaml
> +        <StackLayout VerticalOptions="EndAndExpand"
Removed and using HorizontalStackLayout

2023-10-11 17:45 UTC, jfs-dev commented on task-list-app-maui/Views/EditarTarefaView.xaml
> +    <StackLayout Padding="20">
Using single Grid

2023-10-11 17:46 UTC, jfs-dev commented on task-list-app-maui/Views/TarefasPendentesView.xaml
> +        <ListView x:Name="ListViewTarefasPendentes"
Yes! Can we leave that for the next version?

2023-10-11 17:47 UTC, jfs-dev commented on task-list-app-maui/Views/TarefasPendentesView.xaml.cs
> +public partial class TarefasPendentesView : ContentPage
Can we leave that for the next version?

2023-10-13 16:25 UTC, jfs-dev commented on task-list-app-maui/Views/TarefasConcluidasView.xaml
> +        <ListView x:Name="ListViewTarefasConcluidas"
OK

2023-10-13 16:34 UTC, VladislavAntonyuk requested changes

2023-10-13 16:34 UTC, VladislavAntonyuk commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +        _context = new AppDbContext();
Use DI instead

2023-10-13 16:34 UTC, VladislavAntonyuk commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            Hora = DateTime.Now.TimeOfDay
Please rename properties to English

2023-10-13 16:34 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/AdicionarTarefaView.xaml
> +            <RowDefinition Height="20" />
Please simplify syntax

2023-10-13 16:34 UTC, VladislavAntonyuk commented on task-list-app-maui/Views/EditarTarefaView.xaml
> +              <RowDefinition Height="20" />
Please simplify syntax

2023-10-13 16:38 UTC, jfs-dev commented
Hello! @VladislavAntonyuk 

All pending issues resolved. Please can you rate again?

Planning for upcoming releases in the future:

**Version 1.1**

1. Add User Controls with Property Dependency for Code Reuse in Views;
2. Rename Models, Views, and ViewModels to English;
3. Upgrade .NET 8.0;
4. Upgrade EF Core 8.

**Version 1.2**

1. Implement Search and About interface;
2. Pagination tasks.

**Version 1.3**

1. Implement Login and Create Account interface;
2. Migrate SQLite;
3. Integration with Blazor WebApp via Minimal API.

**Version 1.4**

1. Add tasks by voice command by @VladislavAntonyuk 

**Version Online**

1. WebApp Blazor;
2. Minimal API.

Best Regards.

2023-10-13 20:32 UTC, VladislavAntonyuk commented
Thank you for your changes.
Could you please update to .NET 8 and resolve conflicts?
Also I left some comments in xaml files (mostly related to compatibility/old APIs), which would be nice to fix

2023-10-19 18:58 UTC, jfs-dev commented
Hello! @VladislavAntonyuk 

All pending issues resolved. Please can you rate again?

2023-10-19 19:03 UTC, jfs-dev commented on task-list-app-maui/Views/EditarTarefaView.xaml
> +              <RowDefinition Height="20" />
All ready

2023-10-19 19:04 UTC, jfs-dev commented on task-list-app-maui/Views/AdicionarTarefaView.xaml
> +            <RowDefinition Height="20" />
All ready

2023-10-19 19:04 UTC, jfs-dev commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +        _context = new AppDbContext();
All ready

2023-10-19 19:05 UTC, jfs-dev commented on task-list-app-maui/ViewModels/TarefasViewModel.cs
> +            Hora = DateTime.Now.TimeOfDay
Scheduled for version 1.1

2023-10-19 19:05 UTC, jfs-dev commented on task-list-app-maui/task-list-app-maui.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.11" />
All ready

2023-10-20 13:06 UTC, VladislavAntonyuk commented
The final suggestion. Run dotnet format and commit changes. After that we are good to merge

2023-10-23 20:38 UTC, jfs-dev commented
Done and commit changes! You can proceed

2023-10-24 11:56 UTC, jfs-dev commented
Thanks for the code review.
Should I wait for you to merge?
Do you close the pull?

2023-10-30 20:22 UTC, merged